{TWITTER_KEY: "D3sa8lYN3M6l9S43H2ApQ",
TWITTER_SECRET: "wSewZifMQtiy8KG3CDfhwtXf20cDSHwFzTjYS80g",
OAUTH_TOKEN: "1355396360-dfjbS0wQn67PyCkwYISyTHVSR7TIYlYv1SghMT5",
OAUTH_TOKEN_SECRET: "h2soLfirGBS4QRnZY4d5DxcoBi5FLBfc8lpe2sbLk"}
